server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: test
      password: 1234
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://ohkwang.crmlwf3dfqrm.ap-northeast-2.rds.amazonaws.com:3306/visitbusan
      username: admin
      password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml
    - /mappers/admin/*.xml

file:
  path: C:/project/upload/


