server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 895270230434-lc4ss0hp7cbam449ud1cmms35vtcqjc7.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            client-id: 클라이언트ID
            client-secret: 클라이언트Secret
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
    user:
      name: test
      password: 1234
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://ohkwang.crmlwf3dfqrm.ap-northeast-2.rds.amazonaws.com:3306/visitbusan
      username: admin
      password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml
    - /mappers/admin/*.xml

file:
  path: C:/project/upload/


